name: Sync Leetcode History

on:
  workflow_dispatch:     # Allows manual trigger
  schedule:
    - cron: '0 8 * * *'  # Runs automatically every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run LeetCode Synchronizer
        uses: xidandent/leetcode-synchronizer@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}



